import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/theme-toggle";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CVEThingy",
  description: "Generated by create next app",
};

const Navbar = () => {
  return (
    <div className="flex items-center justify-between w-full text-white bg-black p-3">
      {/* Left-aligned button */}
      <div className="flex-none text-black dark:text-white">
        <ThemeToggle />
      </div>

      {/* Centered text container */}
      <div className="absolute left-1/2 transform -translate-x-1/2">
        <Link href={"/"}>
          <p className="text-2xl text-center">
            KioydioLabs <strong>CVEThingy</strong>
          </p>
        </Link>
      </div>
    </div>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex w-full flex-col mt-0 gap-10 items-center justify-center">
            <Navbar />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
